version: "3.8"

services:
  mariadb:
    image: mariadb:1.0
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress:1.0
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    image: nginx:1.0
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wkannouf/data/db

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wkannouf/data/wordpress

networks:
  inception:

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt